// app/layout.tsx (or app/(site)/layout.tsx)
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css"


const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={manrope.variable}>
      {/* If you want Manrope everywhere by default, use manrope.className instead of .variable */}
      <body className={`${manrope.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
